name = "Oetqf"
uuid = "ba4b8404-3ddb-4226-b41e-638ed858d44e"
authors = ["Pengcheng Shi <shipengcheng1230@gmail.com>"]
version = "0.1.0"

[deps]
BSON = "fbb218c0-5317-5bc6-957e-2ee96dd4b1f0"
DiffEqCallbacks = "459566f4-90b8-5000-8ac3-15dfb0a30def"
Distributed = "8ba89e20-285c-5b6f-9357-94700520ee1b"
FFTW = "7a1cc6ca-52ef-59f5-83cd-3a7055c09341"
GeoGreensFunctions = "1bc39cc2-b9cd-470c-972b-2e3fb46182c5"
GmshTools = "82e2f556-b1bd-5f1a-9576-f93c0da5f0ee"
HDF5 = "f67ccb44-e63f-5c2f-98bd-6dc0ccc4ba2f"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MLStyle = "d8e11817-5142-5d16-987a-aa16d5891078"
OrdinaryDiffEq = "1dea7af3-3e70-54e6-95c3-0bf5283fa5ed"
Parameters = "d96e819e-fc66-5662-9728-84c9c7592b0a"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
RecursiveArrayTools = "731186ca-8d62-57ce-b412-fbd966d074cd"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
Strided = "5e0ebb24-38b0-5f93-81fe-25c709ecae67"

[compat]
DiffEqCallbacks = "2.16"
FFTW = "1.4"
GeoGreensFunctions = "0.1"
GmshTools = "0.5"
HDF5 = "0.15"
MLStyle = "0.4"
OrdinaryDiffEq = "5.53"
Parameters = "0.12"
RecursiveArrayTools = "2.11"
Reexport = "1.0"
Strided = "1.1"
julia = "1.6"
